import {IAnimationOperations} from "./AnimationOperations/Interface/IAnimationOperations";
import {AnimationOperations} from "./AnimationOperations/AnimationOperations";
import {EventUtil, IEventUtil} from "@wessberg/eventutil";
import {IWaitOperations} from "../../Common/Service/WaitOperations/Interface/IWaitOperations";
import {WaitOperations} from "../../Common/Service/WaitOperations/WaitOperations";
import {ISvgIconUtil} from "./SvgIconUtil/Interface/ISvgIconUtil";
import {SvgIconUtil} from "./SvgIconUtil/SvgIconUtil";
import {IAgentDetector} from "./AgentDetector/Interface/IAgentDetector";
import {AgentDetector} from "./AgentDetector/AgentDetector";
import {IGlobalEventBlocker} from "../EventHandler/GlobalEventBlocker/Interface/IGlobalEventBlocker";
import {GlobalEventBlocker} from "../EventHandler/GlobalEventBlocker";
import {INavigationUtil} from "./NavigationUtil/Interface/INavigationUtil";
import {NavigationUtil} from "./NavigationUtil/NavigationUtil";
import {Routes} from "../Router/Routes";
import {IMediaDeviceUtil} from "./MediaDeviceUtil/Interface/IMediaDeviceUtil";
import {MediaDeviceUtil} from "./MediaDeviceUtil/MediaDeviceUtil";
import {IMediaStreamStore} from "../Store/MediaStreamStore/Interface/IMediaStreamStore";
import {MediaStreamStore} from "../Store/MediaStreamStore/MediaStreamStore";
import {IMediaStreamUtil} from "./MediaStreamUtil/Interface/IMediaStreamUtil";
import {MediaStreamUtil} from "./MediaStreamUtil/MediaStreamUtil";
import {IFaceTrackingModelStore} from "../Store/FaceTrackingModelStore/Interface/IFaceTrackingModelStore";
import {FaceTrackingModelStore} from "../Store/FaceTrackingModelStore/FaceTrackingModelStore";
import {IEmotionModelStore} from "../Store/EmotionModelStore/Interface/IEmotionModelStore";
import {EmotionModelStore} from "../Store/EmotionModelStore/EmotionModelStore";
import {IEmotionClassifierUtil} from "./EmotionClassifierUtil/Interface/IEmotionClassifierUtil";
import {EmotionClassifierUtil} from "./EmotionClassifierUtil/EmotionClassifierUtil";
import {EmotionModel} from "../Model/EmotionModel/EmotionModel";
import {IImageSnapUtil} from "./ImageSnapUtil/Interface/IImageSnapUtil";
import {ImageSnapUtil} from "./ImageSnapUtil/ImageSnapUtil";
import {IDebounceOperations} from "./DebounceOperations/Interface/IDebounceOperations";
import {DebounceOperations} from "./DebounceOperations/DebounceOperations";
import {IDOMOperations} from "./DOMOperations/Interface/IDOMOperations";
import {DOMOperations} from "./DOMOperations/DOMOperations";
import {IChildMutationObserver} from "./ChildMutationObserver/Interface/IChildMutationObserver";
import {ChildMutationObserver} from "./ChildMutationObserver/ChildMutationObserver";
import {IStorageUtil} from "./StorageUtil/Interface/IStorageUtil";
import {StorageUtil} from "./StorageUtil/StorageUtil";
import {IEmojiStore} from "../Store/EmojiStore/Interface/IEmojiStore";
import {EmojiStore} from "../Store/EmojiStore/EmojiStore";
import {IDateUtil} from "./DateUtil/Interface/IDateUtil";
import {DateUtil} from "./DateUtil/DateUtil";
import {IGuideStore} from "../Store/GuideStore/Interface/IGuideStore";
import {GuideStore} from "../Store/GuideStore/GuideStore";
import {Guides} from "../Model/Guide/Guides";

export const globalEventBlocker: IGlobalEventBlocker = new GlobalEventBlocker();
export const agentDetector: IAgentDetector = new AgentDetector();
export const eventUtil: IEventUtil = new EventUtil();
export const svgIconUtil: ISvgIconUtil = new SvgIconUtil();
export const waitOperations: IWaitOperations = new WaitOperations();
export const animationOperations: IAnimationOperations = new AnimationOperations();
export const navigationUtil: INavigationUtil = new NavigationUtil(Routes);
export const mediaDeviceUtil: IMediaDeviceUtil = new MediaDeviceUtil();
export const mediaStreamUtil: IMediaStreamUtil = new MediaStreamUtil();
export const storageUtil: IStorageUtil = new StorageUtil();
export const mediaStreamStore: IMediaStreamStore = new MediaStreamStore();
export const emotionModelStore: IEmotionModelStore = new EmotionModelStore(EmotionModel);
export const faceTrackingModelStore: IFaceTrackingModelStore = new FaceTrackingModelStore();
export const emojiStore: IEmojiStore = new EmojiStore();
export const guideStore: IGuideStore = new GuideStore(Guides);
export const emotionClassifierUtil: IEmotionClassifierUtil = new EmotionClassifierUtil(emotionModelStore.getModel());
export const imageSnapUtil: IImageSnapUtil = new ImageSnapUtil();
export const debounceUtil: IDebounceOperations = new DebounceOperations();
export const domUtil: IDOMOperations = new DOMOperations();
export const childMutationObserver: IChildMutationObserver = new ChildMutationObserver();
export const dateUtil: IDateUtil = new DateUtil();